name = "Industrial"

shape = "angular"
relief = "raised"
fill = "auto"
size = 100
background = "gradient"
transparency = 15
key-transparency = 0
edge = "border"
labels = "large"
depth = 6
chamfer = 12
blur = false
