import QtQuick
import Quickshell
import Quickshell.Hyprland
import Quickshell.Io

// Headless singleton: the shell creates one of these per session, whereas the
// bar widget is created once per monitor. Owning the daemons here means there
// is exactly one rotation daemon for the lock to stop.
Item {
  id: root

  // Override from the widget's settings; blank means auto-detect.
  property string tabletSwitchDevice: ""
  property string detectedSwitchDevice: ""
  readonly property string switchDevice: root.tabletSwitchDevice !== "" ? root.tabletSwitchDevice : root.detectedSwitchDevice
  property bool rotationLocked: false
  property bool tabletMode: false
  property bool oskVisible: false

  readonly property string oskDest: "sm.puri.OSK0"
  readonly property string oskPath: "/sm/puri/OSK0"

  function configure(device, locked) {
    root.tabletSwitchDevice = device || ""
    root.rotationLocked = locked
    configureFallback.stop()
    // Locking just means "stop the rotation daemon", which freezes the
    // display at whatever orientation it's currently in.
    rotationProc.running = !locked
  }

  // False until the first switch reading, so "laptop mode" can be told
  // apart from "not polled yet".
  property bool tabletModeKnown: false

  function applySwitchReading(tablet) {
    var first = !root.tabletModeKnown
    root.tabletModeKnown = true
    if (tablet === root.tabletMode && !first) return
    root.tabletMode = tablet
    // Read by the patched menu clone (menu-clone.sh) to pick its focus mode.
    modeWriteProc.command = [
      "sh", "-c",
      'd="${XDG_RUNTIME_DIR:-/tmp}" && printf "%s\\n" "$1" > "$d/fliparchy-mode.tmp" && mv -f "$d/fliparchy-mode.tmp" "$d/fliparchy-mode"',
      "--", tablet ? "tablet" : "laptop"
    ]
    modeWriteProc.running = true
    // The keyboard toggle is hidden outside tablet mode, so the keyboard
    // must be put away here. The first reading counts too: the shell may
    // (re)start while already in laptop mode with the keyboard up.
    if (!tablet) root.setOskVisible(false)
  }

  function toggleOsk() {
    setOskVisible(!root.oskVisible)
  }

  function setOskVisible(visible) {
    oskToggleProc.command = [
      "gdbus", "call", "--session",
      "--dest", root.oskDest,
      "--object-path", root.oskPath,
      "--method", root.oskDest + ".SetVisible",
      visible ? "true" : "false"
    ]
    oskToggleProc.running = true
  }

  // Rotation waits for a widget to report the saved lock state, so a saved
  // lock isn't briefly overridden at startup; unlocked if none reports in.
  Timer {
    id: configureFallback
    interval: 2000
    running: true
    onTriggered: rotationProc.running = !root.rotationLocked
  }

  Process {
    id: rotationProc
    command: ["iio-hyprland"]
    onExited: if (!root.rotationLocked) rotationRestart.start()
  }
  Timer {
    id: rotationRestart
    interval: 3000
    onTriggered: if (!root.rotationLocked) rotationProc.running = true
  }

  Process {
    id: oskProc
    command: ["squeekboard"]
    // Layouts with a Super key, generated by squeekboard-layouts.py; any
    // layout missing there falls back to squeekboard's built-in one.
    environment: ({ SQUEEKBOARD_KEYBOARDSDIR: Quickshell.env("HOME") + "/.local/state/fliparchy/keyboards" })
    onExited: oskRestart.start()
  }
  Timer { id: oskRestart; interval: 3000; onTriggered: oskProc.running = true }

  // Squeekboard only reads GTK CSS at startup. ~/.config/gtk-3.0/gtk.css
  // imports the file written here, so a theme or font change means rewrite
  // then restart. The first write happens before squeekboard's first start.
  readonly property string themeScript:
    Qt.resolvedUrl("squeekboard-theme.sh").toString().replace(/^file:\/\//, "")
  property string themeCss: ""
  property bool themeChecked: false

  Process {
    id: themeProc
    command: ["sh", root.themeScript]
    stdout: StdioCollector {
      onStreamFinished: {
        var first = !root.themeChecked
        root.themeChecked = true
        if (text === "" || text === root.themeCss) {
          if (first) oskProc.running = true
          return
        }
        root.themeCss = text
        themeWriteProc.restartOsk = !first
        themeWriteProc.command = [
          "sh", "-c",
          'd="$HOME/.local/state/fliparchy" && mkdir -p "$d" && printf "%s" "$1" > "$d/squeekboard.css.tmp" && mv -f "$d/squeekboard.css.tmp" "$d/squeekboard.css"',
          "--", text
        ]
        themeWriteProc.running = true
      }
    }
  }
  Process {
    id: themeWriteProc
    property bool restartOsk: false
    // Stopping squeekboard lets oskProc's own exit handler bring it back.
    onExited: if (restartOsk) oskProc.running = false; else oskProc.running = true
  }
  Timer {
    interval: 5000
    running: true
    repeat: true
    triggeredOnStart: true
    onTriggered: if (!themeProc.running) themeProc.running = true
  }

  Process { id: oskToggleProc }
  Process { id: modeWriteProc }

  // Namespaces of overlays patched by overlay-clones.sh. An open overlay
  // covers the bar, so the keyboard is brought up with it; with a stock
  // overlay taps on the keyboard would only close it, so only patched ones
  // count.
  property var patchedOverlays: []
  property var openOverlays: []
  property bool oskShownForOverlay: false

  Process {
    id: patchCheckProc
    command: ["sh", "-c",
      'for p in menu:Menu emojis:Emojis clipboard:Clipboard; do ' +
      'grep -qs "id: fliparchyMode" "$HOME/.config/omarchy/plugins/$USER.${p%%:*}/${p#*:}.qml" && echo "omarchy-${p%%:*}"; ' +
      'done; true']
    running: true
    stdout: StdioCollector {
      onStreamFinished: root.patchedOverlays = text.split("\n").filter(function(s) { return s !== "" })
    }
  }

  Connections {
    target: Hyprland
    function onRawEvent(event) {
      var name = String(event && event.name ? event.name : "")
      if (name !== "openlayer" && name !== "closelayer") return
      var ns = String(event.data || "")
      if (root.patchedOverlays.indexOf(ns) === -1) return
      // Tracked as a set so hopping from one overlay to another (menu to
      // emoji picker) doesn't hide the keyboard when the first one closes.
      var open = root.openOverlays.filter(function(o) { return o !== ns })
      if (name === "openlayer") open.push(ns)
      root.openOverlays = open
      if (name === "openlayer") {
        if (open.length === 1 && root.tabletMode && !root.oskVisible) {
          root.oskShownForOverlay = true
          root.setOskVisible(true)
        }
      } else if (open.length === 0 && root.oskShownForOverlay) {
        root.oskShownForOverlay = false
        root.setOskVisible(false)
      }
    }
  }

  // Find the device reporting SW_TABLET_MODE, whichever driver provides it
  // (lenovo-ymc, intel-vbtn, intel-hid, asus-wmi, hp-wmi, thinkpad_acpi...):
  // the one whose switch bitmask ("B: SW=", last word is bits 0-63) has bit 1.
  // Retried while none is found, e.g. a detachable's keyboard not yet attached.
  function findSwitchDevice(devices) {
    var blocks = devices.split(/\n\s*\n/)
    for (var i = 0; i < blocks.length; i++) {
      var handler = /^H: Handlers=.*\b(event\d+)\b/m.exec(blocks[i])
      var sw = /^B: SW=([0-9a-fA-F ]+)$/m.exec(blocks[i])
      if (!handler || !sw) continue
      var words = sw[1].trim().split(/\s+/)
      if (parseInt(words[words.length - 1], 16) & 2) return "/dev/input/" + handler[1]
    }
    return ""
  }

  Process {
    id: detectProc
    command: ["cat", "/proc/bus/input/devices"]
    stdout: StdioCollector {
      onStreamFinished: root.detectedSwitchDevice = root.findSwitchDevice(text)
    }
  }
  Timer {
    interval: 10000
    running: root.detectedSwitchDevice === ""
    repeat: true
    triggeredOnStart: true
    onTriggered: if (!detectProc.running) detectProc.running = true
  }

  // Poll the tablet-mode switch.
  Process {
    id: tabletModeProc
    command: ["evtest", "--query", root.switchDevice, "EV_SW", "SW_TABLET_MODE"]
    onExited: function(exitCode) { root.applySwitchReading(exitCode === 10) }
  }
  Timer {
    interval: 1000
    running: root.switchDevice !== ""
    repeat: true
    triggeredOnStart: true
    onTriggered: if (!tabletModeProc.running) tabletModeProc.running = true
  }

  // Poll squeekboard's current visibility to keep the icon/tooltip in sync.
  Process {
    id: oskVisProc
    command: [
      "gdbus", "call", "--session",
      "--dest", root.oskDest,
      "--object-path", root.oskPath,
      "--method", "org.freedesktop.DBus.Properties.Get",
      root.oskDest, "Visible"
    ]
    stdout: StdioCollector {
      onStreamFinished: root.oskVisible = text.indexOf("true") !== -1
    }
  }
  Timer {
    interval: 1000
    running: true
    repeat: true
    triggeredOnStart: true
    onTriggered: if (!oskVisProc.running) oskVisProc.running = true
  }
}
