#!/bin/sh
# Prints GTK CSS for squeekboard built from the active Omarchy theme's colours
# and monospace font. Always prints something (a comment on failure) so the
# caller can tell "no theme" from "not finished".

colors="$HOME/.local/state/omarchy/current/theme/colors.toml"

get() {
  sed -n "s/^$1 *= *\"\(#[0-9A-Fa-f]\{6\}\)\".*/\1/p" "$colors" 2>/dev/null | head -n 1
}

bg=$(get background)
key=$(get lighter_background)
fg=$(get foreground)
accent=$(get accent)

if [ -z "$bg" ] || [ -z "$fg" ] || [ -z "$accent" ]; then
  echo "/* fliparchy: no usable Omarchy theme colours; squeekboard defaults apply */"
  exit 0
fi
: "${key:=$bg}"

font=$(omarchy-font-current 2>/dev/null)
font_rule=""
[ -n "$font" ] && font_rule="font-family: \"$font\";"

# Class names mirror squeekboard's built-in style.css. Shades are mixes of the
# theme's own colours, like squeekboard's alpha() tints, so they hold up on
# light and dark themes alike.
cat <<EOF
/* Generated by Fliparchy from the active Omarchy theme; do not edit. */
@define-color fl_bg $bg;
@define-color fl_key $key;
@define-color fl_fg $fg;
@define-color fl_accent $accent;

sq_view {
  background: @fl_bg;
  box-shadow: none;
  $font_rule
}

sq_button {
  color: @fl_fg;
  background: @fl_key;
  $font_rule
}
sq_button:active {
  background: mix(@fl_key, @fl_fg, 0.25);
}

sq_button.altline,
sq_button.special,
sq_button.special-2,
sq_button.special-3,
sq_button.wide,
sq_button.change-view,
sq_button.change-view-2,
sq_button.change-view-3,
sq_button.subtle-highlight,
sq_button.subtle-highlight-2,
sq_button.emoji-group,
sq_button.character-group,
sq_button.fl-mod {
  background: mix(@fl_bg, @fl_fg, 0.12);
  border-color: mix(@fl_bg, @fl_fg, 0.2);
}
sq_button.altline:active,
sq_button.special:active,
sq_button.special-2:active,
sq_button.special-3:active,
sq_button.wide:active,
sq_button.change-view:active,
sq_button.change-view-2:active,
sq_button.change-view-3:active,
sq_button.subtle-highlight:active,
sq_button.subtle-highlight-2:active,
sq_button.emoji-group:active,
sq_button.character-group:active,
sq_button.fl-mod:active {
  background: mix(@fl_bg, @fl_fg, 0.3);
}

sq_button.placeholder,
sq_button.placeholder-2 {
  background: mix(@fl_bg, @fl_fg, 0.04);
}

/* Fliparchy's modifier keys (Ctrl, Alt, Super, Shift), from squeekboard-layouts.py */
sq_button.fl-mod {
  font-size: 0.6em;
}

sq_button.latched {
  background: mix(@fl_key, @fl_accent, 0.5);
  color: @fl_fg;
}
sq_button.locked {
  background: @fl_accent;
  color: @fl_bg;
}

#Return {
  background: @fl_accent;
  color: @fl_bg;
}
#Return:active {
  background: mix(@fl_accent, @fl_fg, 0.3);
  color: @fl_bg;
}
EOF
