#!/bin/sh
# Prints GTK CSS for squeekboard built from the active Omarchy theme's colours
# and monospace font. Always prints something (a comment on failure) so the
# caller can tell "no theme" from "not finished".

colors="$HOME/.local/state/omarchy/current/theme/colors.toml"

get() {
  sed -n "s/^$1 *= *\"\(#[0-9A-Fa-f]\{6\}\)\".*/\1/p" "$colors" 2>/dev/null | head -n 1
}

bg=$(get background)
key=$(get lighter_background)
special=$(get dark_background)
fg=$(get foreground)
accent=$(get accent)
selection=$(get selection)

if [ -z "$bg" ] || [ -z "$fg" ] || [ -z "$accent" ]; then
  echo "/* fliparchy: no usable Omarchy theme colours; squeekboard defaults apply */"
  exit 0
fi
: "${key:=$bg}"
: "${special:=$bg}"
: "${selection:=$accent}"

font=$(omarchy-font-current 2>/dev/null)
font_rule=""
[ -n "$font" ] && font_rule="font-family: \"$font\";"

cat <<EOF
/* Generated by Fliparchy from the active Omarchy theme; do not edit. */
sq_view {
  background-color: $bg;
  $font_rule
}
sq_view sq_button {
  background-color: $key;
  color: $fg;
  $font_rule
}
sq_view sq_button.altline,
sq_view sq_button.special,
sq_view sq_button.wide {
  background-color: $special;
}
sq_view sq_button.latched {
  background-color: $selection;
}
sq_view sq_button.locked,
sq_view sq_button:active {
  background-color: $accent;
  color: $bg;
}
EOF
